[tools]
"gem:overmind" = "latest"
"gem:ruby-lsp" = "latest"
"gem:ruby-lsp-rails" = "latest"
"npm:@agentclientprotocol/claude-agent-acp" = "latest"
"npm:mcp-hub" = "latest"
ast-grep = "latest"
claude = "latest"
claude-powerline = "latest"
direnv = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
lazygit = "latest"
lua = "5.1"
minio = "latest"
neovim = "latest"
node = "latest"
postgres = "latest"
redis = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
zoxide = "latest"
